services:
  call-quality-analyser:
    image: 3cx-call-quality-analyser:latest
    pull_policy: never
    build:
      context: .
    container_name: 3cx-call-quality-analyser
    restart: unless-stopped
    ports:
      - "${CALL_QUALITY_ANALYSER_PORT:-4180}:80"
